package com.example.demo.infrastructure;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class ReportGenerator {

    private static final String SEPARATOR = "========================================";

    // S138: method too long; S1643: String concatenation in loop; S109: magic numbers
    public void generateFullReport() {
        String report = "";
        report += "FULL REPORT\n";
        report += SEPARATOR + "\n";
        report += "Date: " + new java.util.Date() + "\n";
        report += SEPARATOR + "\n";

        List<String> items = new ArrayList<>();
        for (int i = 0; i < 100; i++) {       // S109: magic number
            items.add("item_" + i);
        }

        int totalItems = 0;
        double totalValue = 0.0;
        for (String item : items) {
            totalItems++;
            totalValue += 9.99;                // S109: magic number
            report += "Item: " + item + " value: 9.99\n"; // S1643: in-loop concatenation
        }

        report += SEPARATOR + "\n";
        report += "Total items: " + totalItems + "\n";
        report += "Total value: " + totalValue + "\n";
        report += "Average: " + (totalValue / totalItems) + "\n"; // divide-by-zero if empty
        report += "Tax (21%): " + (totalValue * 0.21) + "\n";     // S109: magic number
        report += "Grand total: " + (totalValue * 1.21) + "\n";   // S109: magic number
        report += SEPARATOR + "\n";
        report += "STATUS: COMPLETE\n";
        report += "Generated by: ReportGenerator v1.0\n";
        report += SEPARATOR + "\n";

        // S2095: FileWriter not in try-with-resources — resource leak on exception
        try {
            FileWriter fw = new FileWriter("report.txt");
            fw.write(report);
            fw.close();
        } catch (IOException e) {
            // S1166: swallowed
        }

        System.out.println("Report generated with " + totalItems + " items");
    }

    public void generateReport(List<String> data, String outputPath) throws InterruptedException {
        if (data == null) {
            return; // S1186: silent return instead of throwing IllegalArgumentException
        }

        StringBuilder sb = new StringBuilder();
        sb.append("DATA REPORT\n");
        sb.append(SEPARATOR).append("\n");

        for (int i = 0; i < data.size(); i++) {
            sb.append(i + 1).append(". ").append(data.get(i)).append("\n");
            if (i % 50 == 0) {          // S109: magic number
                Thread.sleep(10);       // S109: magic number; no interrupt check
            }
        }

        sb.append(SEPARATOR).append("\n");
        sb.append("Total: ").append(data.size()).append("\n");

        // S2095: resource leak
        try {
            FileWriter fw = new FileWriter(outputPath);
            fw.write(sb.toString());
            fw.close();
        } catch (IOException e) {
            System.err.println("Failed to write report");
        }
    }
}
